GRANT OWNERSHIP ON DATABASE PLATFORM_DB TO ROLE PLATFORM_ADMIN_ROLE;

GRANT OWNERSHIP ON DATABASE GOVERNANCE_DB TO ROLE PLATFORM_ADMIN_ROLE;

GRANT OWNERSHIP ON DATABASE AUDIT_DB TO ROLE PLATFORM_ADMIN_ROLE;

GRANT OWNERSHIP ON WAREHOUSE PLATFORM_WH TO ROLE PLATFORM_ADMIN_ROLE;

GRANT OWNERSHIP ON WAREHOUSE GOVERNANCE_WH TO ROLE PLATFORM_ADMIN_ROLE;