DEFINE ROLE PLATFORM_ADMIN_ROLE;
DEFINE ROLE PLATFORM_RW_ROLE;
DEFINE ROLE PLATFORM_RO_ROLE;

DEFINE ROLE INGESTION_ADMIN_ROLE;
DEFINE ROLE INGESTION_RW_ROLE;
DEFINE ROLE INGESTION_RO_ROLE;

DEFINE ROLE SADP_ADMIN_ROLE;
DEFINE ROLE SADP_RW_ROLE;
DEFINE ROLE SADP_RO_ROLE;

DEFINE ROLE DOMAIN_CUSTOMER_ADMIN_ROLE;
DEFINE ROLE DOMAIN_CUSTOMER_RW_ROLE;
DEFINE ROLE DOMAIN_CUSTOMER_RO_ROLE;

DEFINE ROLE DOMAIN_FINANCE_ADMIN_ROLE;
DEFINE ROLE DOMAIN_FINANCE_RW_ROLE;
DEFINE ROLE DOMAIN_FINANCE_RO_ROLE;