GRANT ROLE PLATFORM_RW_ROLE TO ROLE PLATFORM_ADMIN_ROLE;

GRANT ROLE PLATFORM_RO_ROLE TO ROLE PLATFORM_ADMIN_ROLE;

GRANT ROLE INGESTION_RW_ROLE TO ROLE INGESTION_ADMIN_ROLE;

GRANT ROLE INGESTION_RO_ROLE TO ROLE INGESTION_ADMIN_ROLE;

GRANT ROLE SADP_RW_ROLE TO ROLE SADP_ADMIN_ROLE;

GRANT ROLE SADP_RO_ROLE TO ROLE SADP_ADMIN_ROLE;

GRANT ROLE DOMAIN_CUSTOMER_RW_ROLE TO ROLE DOMAIN_CUSTOMER_ADMIN_ROLE;

GRANT ROLE DOMAIN_CUSTOMER_RO_ROLE TO ROLE DOMAIN_CUSTOMER_ADMIN_ROLE;

GRANT ROLE DOMAIN_FINANCE_RW_ROLE TO ROLE DOMAIN_FINANCE_ADMIN_ROLE;

GRANT ROLE DOMAIN_FINANCE_RO_ROLE TO ROLE DOMAIN_FINANCE_ADMIN_ROLE;